### ISSUE TITLE
Periodic objective breaks subLHCoptim

### ISSUE THREAD

**Issue by eelregit** [MrUrq/LatinHypercubeSampling.jl#11]
by the following line
https://github.com/MrUrq/LatinHypercubeSampling.jl/blob/85e6f5ae54265aac2de2bc607dacfd0c86f719e8/src/AudzeEglaisObjective.jl#L12
Instead `n` of the superset should be used here.

**Comment by eelregit** [comment]
BTW is the optimization parallelized? With the periodic function, the optimization seems to plateau much later. So I will have to wait for weeks if the optimization is done serially. Thanks.

**Comment by MrUrq** [comment]
Thanks for opening the issue. I have been short on time lately but I've now implemented the fix in master. Please have a look and I will bump the version if you think it is fine. 

Currently there is no parallelization in place. This would of course be very desirable. I did some experiments with it several Julia versions ago but the overhead was too large and did not give any speedup for the moderately sized plans I tried. With current Julia versions, and the improvements that have been made to the threaded side of Julia, I think this would be possible without too much effort. 

I have tried to pick off the major low hanging fruits performance-wise in this package but there is still some room for single-threaded performance as well. 

If you want to take a stab at it, I would appreciate pull requests of either single-threaded performance improvements or multi-threading!

**Comment by eelregit** [comment]
Thanks! The fix looks great. I can look into the parallelization when I know julia better ;)
