### ISSUE TITLE
User interface point for random number generator

### ISSUE THREAD

**Issue by ablaom** [MrUrq/LatinHypercubeSampling.jl#15]
Is there a way the user can specify an RNG different from GLOBAL_RNG for the sampling (important for reproducibility)?

**Comment by MrUrq** [comment]
Thank you for bringing this to my attention. The master branch now has the possibility to set RNG with the `rng` keyword and accepts any `rng <: AbstractRNG`. Please let me know if this works for you and I will work on releasing this soon.

**Comment by MrUrq** [comment]
The update is now available in the tagged version 1.7.0 and is accessible with the `rng` keyword.

**Comment by ablaom** [comment]
Wow. That was a fast response!

We should have an [MLJ integration](https://github.com/alan-turing-institute/MLJTuning.jl/pull/83) very soon. Any comment on the PR very welcome.
