### ISSUE TITLE
Extend compat for StatsBase.jl to include version 0.34

### ISSUE THREAD

**Issue by ablaom** [MrUrq/LatinHypercubeSampling.jl#23]
This is holding up some downstream packages. For example MLJ.jl via MLJTuning.jl

**Comment by ablaom** [comment]
BTW. Looks like CompatHelper needs kicking back to life.

**Comment by MrUrq** [comment]
Thanks for the heads up. This is now fixed in version 1.9.0.

**Comment by ablaom** [comment]
Thanks for the lightning response ❤️
